# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan de Zille
email: dan@ddez.net
description: > # this means to ignore newlines until "baseurl:"
  This is the personal site of all round geek Dan de Zille
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dandezille.github.io" # the base hostname & protocol for your site
twitter_username: dandezille
github_username:  dandezille

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
