[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://www.googletagmanager.com https://www.google-analytics.com"
